- name: set up todoapp project
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    
    - name: start service
      systemd:
        name: nginx
        state: started
        enabled: yes



