- name: Install Npm
  apt:
    name: npm
    update_cache: yes
    state: present

- name: Download Artificats from Nexus
  include_tasks: download-nexus-artifacts.yml

- name: setup SystemD service
  include_tasks: setup-systemd.yml